### ISSUE TITLE
您好，请问还维护此项目嘛？什么时候添加对图片的支持，比如增加Glide 加载

### ISSUE THREAD

**Issue by liuxuesong001** [guosen/TextViewForHTml#1]
您好，请问还维护此项目嘛？什么时候添加对图片的支持，比如增加Glide 加载

**Comment by guosen** [comment]
可以参照 https://github.com/guosen/TextViewForHTml/blob/master/app/src/main/java/com/sen/textviewforhtml/HtmlImageGetter.java
有问题联系Q1432967264 一起讨论

**Comment by guosen** [comment]
> 您好，请问还维护此项目嘛？什么时候添加对图片的支持，比如增加Glide 加载

可以参照 https://github.com/guosen/TextViewForHTml/blob/master/app/src/main/java/com/sen/textviewforhtml/HtmlImageGetter.java
有问题联系Q1432967264 一起讨论
